apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-eta-test-deploy
  labels:
    app: healthcare-eta-app
    environment: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-eta-app
      environment: test
  template:
    metadata:
      labels:
        app: healthcare-eta-app
        environment: test
    spec:
      containers:
      - name: healthcare-eta-container
        image: bhanjatwinkle/healthcare-eta-app
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-test-service
  labels:
    app: healthcare-eta-app
    environment: test
spec:
  selector:
    app: healthcare-eta-app
    environment: test
  type: NodePort
  ports:
  - nodePort: 31034    
    port: 8083
    targetPort: 8083
